import type { Metadata } from "next";
import { ClerkProvider, Show, UserButton } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Clerk Next.js Quickstart",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <ClerkProvider>
                    <Navbar/>
                    {children}
                    <footer className="flex justify-center items-center p-4 gap-4 h-16 border-t">
                        <p className="text-sm text-gray-500">
                            &copy; {new Date().getFullYear()} ToDo App. All
                            rights reserved.
                        </p>
                    </footer>
                </ClerkProvider>
            </body>
        </html>
    );
}
