import type { Metadata } from "next";
import { ClerkProvider, Show, UserButton } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Clerk Next.js Quickstart",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <ClerkProvider>
                    <header className="flex justify-between items-center p-4 gap-4 h-16">
                        <Show when="signed-out">
                            <Link href="/">
                                <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
                                    ToDo App
                                </h1>
                            </Link>
                            <div>
                                <Link href="/sign-in">
                                    <Button variant="ghost">Sign In</Button>
                                </Link>
                                <Link href="/sign-up">
                                    <Button>Sign Up</Button>
                                </Link>
                            </div>
                        </Show>
                        <Show when="signed-in">
                            <Link href="/dashboard">
                                <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
                                    ToDo App
                                </h1>
                            </Link>
                            <UserButton />
                        </Show>
                    </header>
                    {children}                
                </ClerkProvider>
            </body>
        </html>
    );
}
